# Generated by Django 3.0.5 on 2020-04-17 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20200417_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatsessionmember',
            name='chat_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='chat.ChatSession'),
        ),
        migrations.AlterField(
            model_name='chatsessionmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatsessionmessage',
            name='chat_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='chat.ChatSession'),
        ),
        migrations.AlterField(
            model_name='chatsessionmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
