# Generated by Django 2.0.1 on 2020-05-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200417_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsessionmessage',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
    ]
