# Generated by Django 3.0.5 on 2020-05-10 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_chatsessionmessage_isread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsessionmessage',
            name='isRead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readers', to=settings.AUTH_USER_MODEL),
        ),
    ]
