# Generated by Django 3.0.5 on 2020-05-10 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20200510_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsessionmessage',
            old_name='user',
            new_name='owner',
        ),
    ]
